package com.dreamchaser.depository_manage.entity;

import java.util.Date;

/**
 * notice
 * 
 * @author bianj
 * @version 1.0.0 2021-06-14
 */
public class Notice implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2744388334561767209L;


    /** 公告主键 */
    private Integer id;

    /** 公告标题 */
    private String title;

    /** 公告内容 */
    private String content;

    /** 发布时间 */
    private Date time;


    /**
     * 获取公告主键
     * 
     * @return 公告主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置公告主键
     * 
     * @param id
     *          公告主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取公告标题
     * 
     * @return 公告标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * 设置公告标题
     * 
     * @param title
     *          公告标题
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 获取公告内容
     * 
     * @return 公告内容
     */
    public String getContent() {
        return this.content;
    }

    /**
     * 设置公告内容
     * 
     * @param content
     *          公告内容
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取发布时间
     * 
     * @return 发布时间
     */
    public Date getTime() {
        return this.time;
    }

    /**
     * 设置发布时间
     * 
     * @param time
     *          发布时间
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}