package com.dreamchaser.depository_manage.entity;

/**
 * standing_book
 * 
 * @author bianj
 * @version 1.0.0 2021-05-20
 */
public class StandingBook {
    /** 版本号 */
    private static final long serialVersionUID = 7203535351933957406L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 台账记录id */
    private Integer id;

    /** 0表示调入，1表示调出（外部）;2表示调入（退料），3表示调出（领料）（内部调用） */
    private Integer type;

    /** 数量 */
    private Integer quantity;

    /** 总价 */
    private Integer price;

    /** 材料名称 */
    private String materialName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取台账记录id
     * 
     * @return 台账记录id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置台账记录id
     * 
     * @param id
     *          台账记录id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取0表示调入，1表示调出（外部）;2表示调入（退料），3表示调出（领料）（内部调用）
     * 
     * @return 0表示调入
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * 设置0表示调入，1表示调出（外部）;2表示调入（退料），3表示调出（领料）（内部调用）
     * 
     * @param type
     *          0表示调入
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取数量
     * 
     * @return 数量
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * 设置数量
     * 
     * @param quantity
     *          数量
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * 获取总价
     * 
     * @return 总价
     */
    public Integer getPrice() {
        return this.price;
    }

    /**
     * 设置总价
     * 
     * @param price
     *          总价
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * 获取材料名称
     * 
     * @return 材料名称
     */
    public String getMaterialName() {
        return this.materialName;
    }

    /**
     * 设置材料名称
     * 
     * @param materialName
     *          材料名称
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}