package com.dreamchaser.depository_manage.entity;

/**
 * transfer_record
 * 
 * @author bianj
 * @version 1.0.0 2021-06-05
 */
public class TransferRecord implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1696077392188910210L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 转移记录id */
    private Integer id;

    /** 转出仓库id */
    private Integer fromId;

    /** 转入仓库id */
    private Integer toId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取转移记录id
     * 
     * @return 转移记录id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置转移记录id
     * 
     * @param id
     *          转移记录id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取转出仓库id
     * 
     * @return 转出仓库id
     */
    public Integer getFromId() {
        return this.fromId;
    }

    /**
     * 设置转出仓库id
     * 
     * @param fromId
     *          转出仓库id
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * 获取转入仓库id
     * 
     * @return 转入仓库id
     */
    public Integer getToId() {
        return this.toId;
    }

    /**
     * 设置转入仓库id
     * 
     * @param toId
     *          转入仓库id
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}