package com.dreamchaser.depository_manage.entity;

import java.util.Date;

/**
 * user
 * 
 * @author bianj
 * @version 1.0.0 2021-05-05
 */
public class User {

    /** 用户id */
    private Integer id;

    /** 用户名称 */
    private String uname;

    /** 表示权限等级 */
    private String authority;

    /** 用户登录密码（数据库存储的是加密后的） */
    private String pwd;

    /** 性别 */
    private String sex;

    /** 负责仓库，序号表示仓库id，0表示全部仓库 */
    private Integer depositoryId;

    /** 入职日期 */
    private Date entryDate;

    /** 邮箱 */
    private String email;

    /** 手机号 */
    private String phone;

    /**
     * 获取用户id
     * 
     * @return 用户id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置用户id
     * 
     * @param id
     *          用户id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取用户名称
     * 
     * @return 用户名称
     */
    public String getUname() {
        return this.uname;
    }

    /**
     * 设置用户名称
     * 
     * @param uname
     *          用户名称
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * 获取表示权限等级
     * 
     * @return 表示权限等级
     */
    public String getAuthority() {
        return this.authority;
    }

    /**
     * 设置表示权限等级
     * 
     * @param authority
     *          表示权限等级
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    /**
     * 获取用户登录密码（数据库存储的是加密后的）
     * 
     * @return 用户登录密码（数据库存储的是加密后的）
     */
    public String getPwd() {
        return this.pwd;
    }

    /**
     * 设置用户登录密码（数据库存储的是加密后的）
     * 
     * @param pwd
     *          用户登录密码（数据库存储的是加密后的）
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * 获取性别
     * 
     * @return 性别
     */
    public String getSex() {
        return this.sex;
    }

    /**
     * 设置性别
     * 
     * @param sex
     *          性别
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * 获取负责仓库，序号表示仓库id，0表示全部仓库
     * 
     * @return 负责仓库
     */
    public Integer getDepositoryId() {
        return this.depositoryId;
    }

    /**
     * 设置负责仓库，序号表示仓库id，0表示全部仓库
     * 
     * @param depositoryId
     *          负责仓库
     */
    public void setDepositoryId(Integer depositoryId) {
        this.depositoryId = depositoryId;
    }

    /**
     * 获取入职日期
     * 
     * @return 入职日期
     */
    public Date getEntryDate() {
        return this.entryDate;
    }

    /**
     * 设置入职日期
     * 
     * @param entryDate
     *          入职日期
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * 获取邮箱
     * 
     * @return 邮箱
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * 设置邮箱
     * 
     * @param email
     *          邮箱
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 获取手机号
     * 
     * @return 手机号
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * 设置手机号
     * 
     * @param phone
     *          手机号
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}